name: Build - Ubuntu (Dev)

on:
  workflow_dispatch:

  push:
    branches: [ mychanges ]
    paths:
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "data/**"
      - "tests/**"

  pull_request:
    branches: [ mychanges ]
    paths:
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  MAKEFLAGS: "-j4"

jobs:
  build:
    name: Build linux-release (ubuntu-24.04)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache ninja-build gcc-14 g++-14

      - name: Set GCC 14 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          max-size: "2G"
          key: ccache-ubuntu24-release-${{ github.ref }}
          restore-keys: |
            ccache-ubuntu24-release-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
          vcpkgGitCommitId: ${{ hashFiles('vcpkg.json') }}   # better caching

      - name: Configure & Build
        uses: lukka/run-cmake@v10.8
        with:
          configurePreset: linux-release
          buildPreset: linux-release
          buildToolOptions: "-j4"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canary-ubuntu24-release
          path: build/linux-release/bin/
